---
- hosts: all
  become: yes
  tasks:

      - name: Create a new ext4 primary partition
        parted:
          device: /dev/sdb
          number: 1
          state: present
          fs_type: ext4
        when: ansible_devices.sdb is defined

      - name: Create a volume group on top of /dev/sdb with physical extent size = 128KiB
        lvg:
         vg: vg0
         pvs: /dev/sdb1
        when: ansible_devices.sdb.partitions.sdb1 is defined and ansible_lvm.vgs.vg0 is not defined 
      - name: vg test
        debug:
         msg: "Volume group doesn't exist" 
        when: ansible_lvm.vgs.vg0 is not defined
      
      - name: Create a logical volume of 1500m
        lvol:
         vg: vg0
         lv: lv0
         size: 1500
        when: (ansible_lvm.vgs.vg0 is defined ) and (ansible_lvm.vgs.vg0.size_g | float ) > 1.5 
 
   
      - name: debug lg1500
        debug:
          msg: "Not enough space for logical volume" 
        when: (ansible_lvm.vgs.vg0 is defined) and (ansible_lvm.vgs.vg0.size_g | float ) < 1.5


      - name: Create a logical volume of 800m
        lvol:
         vg: vg0
         lv: lv0
         size: 800
        when: (ansible_lvm.vgs.vg0 is defined ) and (ansible_lvm.vgs.vg0.size_g | float ) < 1.5

      - name: Create a ext4 filesystem on /dev/sdb1 and check disk blocks
        filesystem:
         fstype: xfs
         dev: /dev/mapper/vg0-lv0
        when: (ansible_lvm.vgs.vg0 is defined ) and (ansible_lvm.lvs.lv0 is defined )
